#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/nso-example-jwt-auth.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module nso-example-jwt-auth.yang


class ns(object):
    hash = 1484220814

    id = "urn:nso-example-jwt-auth"

    uri = "urn:nso-example-jwt-auth"

    prefix = "nso-example-jwt-auth"

    nso_example_jwt_auth_token = 1808732283
    nso_example_jwt_auth_token_ = "token"
    nso_example_jwt_auth_secret = 1322085478
    nso_example_jwt_auth_secret_ = "secret"
    nso_example_jwt_auth_algorithm = 498368323
    nso_example_jwt_auth_algorithm_ = "algorithm"
    nso_example_jwt_auth_get_token = 706730741
    nso_example_jwt_auth_get_token_ = "get-token"
    nso_example_jwt_auth_jwt_auth = 2000325709
    nso_example_jwt_auth_jwt_auth_ = "jwt-auth"
    actionpoint_jwt_auth_get_token = "jwt-auth-get-token"
